- html lang="en":
    - head:
        - link rel="stylesheet" href="/public/theme.css":
        - script src="./public/renderJmpl.js" defer type="module":
        - script src="https://cdn.jsdelivr.net/npm/construct-style-sheets-polyfill@3.1.0/dist/adoptedStyleSheets.min.js":
        - script src="https://cdn.jsdelivr.net/npm/@rettangoli/ui@0.1.2-rc32/dist/rettangoli-iife-ui.min.js":
    - body.dark:
      - "${content}"